### ISSUE TITLE
Skeleton application with Twig enabled errors out of the box

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-expressive-skeleton#126]
I will admit I am totally out of my depth here, but I would not expect the skeleton application to generate an error out of the box.

I used the following options:
 * No
 * Zend Router
 * Zend ServiceManager
 * Twig

And I see the following error:

`Deprecated: Zend\Expressive\Twig\TwigRendererFactory now expects you to register the factory Zend\Expressive\Twig\TwigEnvironmentFactory for the service Twig_Environment; please update your dependency configuration. in /Users/GeeH/www/slides/vendor/zendframework/zend-expressive-twigrenderer/src/TwigRendererFactory.php on line 94`

I hopefully will get a PR in soon but wanted to make sure it's caught in case I forget.

**Comment by GeeH** [comment]
@xtreamwayz - this looks like it would be quite straightforward but I ran into a brick wall, is this something you can look at please?

**Comment by xtreamwayz** [comment]
@GeeH It's just a deprecated message caused by this: https://github.com/zendframework/zend-expressive-twigrenderer/blob/master/src/TwigRendererFactory.php#L88

It's correctly added in the develop branch.

This should be the dependencies in `config/autoload/templates.global.php`.

    'dependencies' => [
        'factories' => [
            Twig_Environment::class => TwigEnvironmentFactory::class,
            TemplateRendererInterface::class => TwigRendererFactory::class,
        ],
    ],

But yes, I agree. The deprecation message shouldn't be there if you create a new project. What I can do is create a PR with the correct factories and release a new bugfix version for the skeleton.

**Comment by xtreamwayz** [comment]
Uhm, nothing should be removed but this line should be added:

    Twig_Environment::class => Zend\Expressive\Twig\TwigEnvironmentFactory::class,

I'll make a PR right now.

**Comment by xtreamwayz** [comment]
Fixed in version [1.0.5](https://github.com/zendframework/zend-expressive-skeleton/releases/tag/1.0.5). Thanx for reporting @GeeH.

**Comment by GeeH** [comment]
@xtreamwayz Geert, thank you so much for such a quick turn around. Next time we meet in person I definitely owe you a :beer:.
