### ISSUE TITLE
Feature: Include error logging, discussion ?

### ISSUE THREAD

**Issue by belgattitude** [zendframework/zend-expressive-skeleton#158]
Wondering about the inclusion of a standard error logger in the skeleton (psr/log).

see https://discourse.zendframework.com/t/errorhandler-with-logger-should-be-in-skeleton/138

Would be happy to P/R, but I had some questions in mind:

1. Do you think it fits in the skeleton (as I am), or an independant repo (like expressive-errorlogger, more opinionated) ? 

2. The current doc makes use of [delegators](https://docs.zendframework.com/zend-expressive/features/container/delegator-factories/), see  [docs for error handling](https://docs.zendframework.com/zend-expressive/features/error-handling/). How can it be emulated with Pimple or Aura.DI ?

3. Config file ? Where to store it (errorlogger.global.php...) ? `NullLogger` by default and suggested use of monolog ?  If using a `LoggingErrorListenerDelegatorFactory`, would it be placed in `dependencies.global.php` or in the config file ?

4. If creating a default `LoggingErrorListenerDelegatorFactory`... what would be the namespace (App\Infrastructure\Log, App\Skeleton\Log) ?

**Comment by weierophinney** [comment]
I would argue the following:

- It should be a separate component. This fact also answers your last question (number 4), as the component would have its own namespace.
- That component would define a `ConfigProvider`, and add it to its `composer.json` so it can be discovered by zend-component-installer. This partially answers question 3.
- The `ConfigProvider` would register a delegator on the `ErrorHandler` to auto-register it. As noted in the forum post, delegator factories are supported across all supported DI container implementations by the skeleton since the 2.0 release. This answers question 2.
- I would have the log listener compose a service with a discrete name that should resolve to a PSR-3 logger, but not use the service name `Psr\Log\LoggerInterface`; this will allow having multiple loggers in your system. A developer could always alias the custom service name to the PSR-3 logger service to re-use it. As such, the only configuration would be of dependencies; how the logger itself is configured would be up to whatever package provides the PSR-3 implementation and/or how the application developer wants to configure the logger. This completes the answer to question 3.
- It should use `Psr\Log\NullLogger` by default; i.e., the service name representing the component-specific logger should provide an instance of that class by default.

This approach means that the skeleton would not need to incorporate it by default, which is generally a good thing; more services == more overhead, especially as this would be present on _every_ request, even if no logging occurs. We could add a question to the installer to ask if error logging should be enabled, and, if so, we'd add this component.

Users who do not add it during initial install could require it later, or even require it strictly in development.

**Comment by belgattitude** [comment]
Hi Matthew, 

thanks you so much for the clear explanation, that's really giving me a lot of confidence with expressive. I'll see what I can do with your advices...
