### ISSUE TITLE
Don't ask about HttpHandlerRunner's ConfigProvider on installation

### ISSUE THREAD

**Issue by akrabat** [zendframework/zend-expressive-skeleton#207]
When running `composer create-project "zendframework/zend-expressive-skeleton:3.0.0alpha1 test`, I'm asked:

> Please select which config file you wish to inject 'Zend\HttpHandlerRunner\ConfigProvider' into

This should not happen as it's meaningless to the user and the app doesn't work if you answer 'n'.

Possibly related to #204?

**Comment by xtreamwayz** [comment]
For now you have to answer yes to installing the ConfigProviders. It contains all the configuration to get a working application out-of-the-box. If you answer no to any of the ConfigProvider questions you need to add those manually to `./config/config.php` or copy its config to a file in `./config/autoload/*.global.php`. 

That question is asked for every package installed with a ConfigProvider if you answered no the second part. This is how the component-installer works and yes, that's why I opened #204. The idea is to prevent questions for all white listed packages to give a smoother user experience.

I'll leave this open for now to prevent multiple reports and to remind me to add it to the component installer.
