### ISSUE TITLE
Build ArrayObject from array

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/zend-expressive-skeleton#43]
https://github.com/zendframework/zend-expressive-skeleton/blob/master/config/config.php#L35

It make sense to build ArrayObject instance when I don't use a Aura.Di?

**Comment by mtymek** [comment]
After creating a project based on skeleton, you are free to tweak - if you are not using Aura.Di, then you can remove this line from your code.

For the purpose of flexibility, I decided to remove ArrayObject from my config library: https://github.com/mtymek/expressive-config-manager/pull/5.

**Comment by xtreamwayz** [comment]
@snapshotpl You can safely remove it in your case. It's just there so we only have 1 config file to maintain.

@mtymek Wouldn't it be better to leave it there "for the purpose of flexibility"? Without it you can't use the Aura.Di container and it would make it less flexible.

**Comment by mtymek** [comment]
See my updated PR (#31) - I moved creating `ArrayObject` from ConfigManager back to `config.php` file.  No harm done for Aura.Di support.

**Comment by xtreamwayz** [comment]
I just noticed while testing the code. As long as it is in ``config.php`` it's working.

**Comment by snapshotpl** [comment]
Ok, but why not to move creation of ArrayObject here https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/Resources/config/container-aura-di.php#L13 ? What if container required array (type hinting)? We need to use `getArrayCopy()`?

**Comment by xtreamwayz** [comment]
Moving to the aura.di specific container file might work. But than you have inconsistency between different containers. If you use aura.di it's an ArrayObject and when using other container you have an array.

> What if container required array (type hinting)? We need to use getArrayCopy()?

If an array is required, you can simply use ``functionName((array) $config)``.

The beauty of Zend Expressive is that you can set it up the way you want and you can use any library you want. It's also a bit of an issue for an installer like this since you need to keep it compatible with different libraries and preferably consistent.

It's easy enough to tweak the app as you want it to be after installation. In your case you can easily remove it.

@weierophinney Any thoughts on this?

**Comment by weierophinney** [comment]
I'd prefer to keep the casting to `ArrayObject`. As noted, it simplifies swapping out the container; if we have different types for the `config` service based on the container used, factories are then going to need to differ based on the container used.
