### ISSUE TITLE
Access /path/to/public got 404 page

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive-skeleton#51]
While there is .htaccess, I am thinking we can do direct call /path/to/expressive/public in browser, but it got 404 page. Is it a .htacces config issue ?

**Comment by samsonasik** [comment]
this maybe on `Zend\Expressive\Router` path with adding leading directory accessed before "/" ?

**Comment by mtymek** [comment]
This happens because Expressive has no support for "base path" - it puts whole "/path/to/expressive/public" into your router, leading to 404 page.
Fixing this would require additional middleware - I was able to quickly find this one: https://github.com/Lansoweb/basepath.

**Comment by samsonasik** [comment]
hm.., probably make this a default feature ?

**Comment by mtymek** [comment]
I would say no. In most cases you will have your application running directly under the domain, without extra path. Development environment is also not a problem since you can use PHP's built-in HTTP server. Detection logic is complex ([see here](https://github.com/zendframework/zend-http/blob/master/src/PhpEnvironment/Request.php#L491)) - while it may be not slowing your application down too much, I don't think it is elegant to have it around if it is not required in 90% cases.

IMO it should be described in a cookbook.

**Comment by samsonasik** [comment]
@weierophinney any opinion for it?

**Comment by xtreamwayz** [comment]
Not sure if this helps, but you can add ``RewriteBase`` to .htaccess.
In your case ``RewriteBase /path/to/expressive/public``.

If that doesn't work there are some more options:
- use ``php -S 0.0.0.0:8080 -t public/``
- as mtymek says, use https://github.com/Lansoweb/basepath (I didn't try but it looks like that's what you want to use)
- in stead of placing projects under localhost/path/to/project/public, configure apache so each project is accessible under ``sitename.localhost``. Then the projects are served from the root and you don't have that issue.

I don't think there shouldn't be a built in option for this since you open up all files in your project. (I hope this is your local server.) e.g. I could access server.com/path/to/expressive/config/autoload/database.local.php.

**Comment by samsonasik** [comment]
RewriteBase doesn't work. Yes, I know about the options, just wondering if we can do like zf2 without vhost or PHP CLI Server. 

In live app, the assumption we set `config/` folder secure with .htaccess config, so, that can be prevented for user to see.

**Comment by mtymek** [comment]
I built a little project that can help you with serving your app from subdirectories: https://github.com/mtymek/blast-base-url

**Comment by samsonasik** [comment]
Thank you! I think it would be great to have it in cookbook ;)
