### ISSUE TITLE
Composer versions mismatch when creating skeleton project

### ISSUE THREAD

**Issue by lferro9000** [zendframework/zend-expressive-skeleton#79]
When trying to setup PSR7-Sessions just after creating a new skeleton project, the dependencies installed are not compatible between them.

One has to perform a composer update before installing it (as documented in):

https://github.com/Ocramius/PSR7Session/issues/47

This is not a big deal, but should either be corrected on the command level or documents on the instalation guides to avoid new developers getting stuck with composer issues.

Cheers,
LF

**Comment by Ocramius** [comment]
To clarify what is going on here: the `composer.json` and `composer.lock` don't correspond. Running a `composer update` after running the expressive installer causes some changes in the environment. This is because the [installer `config.php`](https://github.com/zendframework/zend-expressive-skeleton/blob/8f3a07d0a2025abb5ae16080e226c86611a57c40/src/ExpressiveInstaller/config.php#L4-L16) is [just copied to `composer.json`](https://github.com/zendframework/zend-expressive-skeleton/blob/8f3a07d0a2025abb5ae16080e226c86611a57c40/src/ExpressiveInstaller/OptionalPackages.php#L173).

In general, this means that the composer execution is modified with packages that don't correspond the current `composer.json` execution, causing (for example) `ocramius/proxy-manager:2.0.1` to be installed, while `ocramius/proxy-manager:^1.0` is written to the `composer.json`

**Comment by Ocramius** [comment]
Note that composer doesn't reload the `composer.json` contents after a `pre-install-cmd` or a `pre-update-cmd`: that's the actual problem.

**Comment by xtreamwayz** [comment]
@Ocramius Is there anyway composer can be forced to reload the `composer.json` file that you know of?

**Comment by Ocramius** [comment]
Not as far as I know.

**Comment by xtreamwayz** [comment]
@ocramius The actual problem was that the version constrain was never set for an added package. That caused composer to load the latest available package, even if it was a higher version than the actual required version string.
