### ISSUE TITLE
Let ExpressiveInstaller also delete md files

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-expressive-skeleton#98]
Wouldn't it make sense to let the ExpressiveInstaller also delete the .md files?
Keeping the CHANGELOG.md, README.md and CONTRIBUTING.md (or rather their contents) wouldn't make sense if a new project based on the skeleton is being created.
Judging by the content of the LICENSE.md i guess that file won't get removed in any case and the CONDUCT.md is debatable. Maybe the user could be asked if he wants to keep it.

**Comment by xtreamwayz** [comment]
There are too many questions already. Either they should be removed automatically or not. I don't mind them being there. I can think of some reasons to keep those and remove those.

One of the reasons to keep the readme and changelog is if someone started a new project and he wants to know where the docs are or maybe what changed since the last time he started a new project.
Same goes for contribution, if someone finds an issue he can read about how to create a pr.

**Comment by Koopzington** [comment]
But the contents of those files are only relevant if someone actually develops "zend-expressive-skeleton" and not a project based on the skeleton. Pointing to mail adresses and websites of Zend in a project not even related to Zend 'cept for the fact that it uses Zend doesn't make sense to me.

If i checkout that skeleton and create an application based on it and put it on GitHub, i wouldn't want to tell the contributors to send mails to Zend in case they find any critical security issues in my code.
If people are lazy or don't know what they do, they'd commit those files right away without even checking their contents. I'd rather let those files get deleted by the Installer and let user create them manually if they feel like they need them in their projects.

**Comment by xtreamwayz** [comment]
I copied most behaviour from ZendSkeletonApplication. Nothing is removed in there. It even includes the TODO.md file.

Like I said, feel free to create a PR to remove those files. I don't care if they are removed or not. But I don't agree that a reason for removal is that developers are lazy or there is a serious lack of code review in some organisations.
